name: Send Phone Notification

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Open YouTube
        shell: cmd
        run: |
          C:\Users\darkg\Downloads\platform-tools-latest-windows\platform-tools\adb.exe shell am start -n com.google.android.youtube/.app.honeycomb.Shell
